version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - webapp-net
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./db/init.sql:/init.sql
  sql-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    entrypoint: /bin/bash
    command: >
      -c "
      sleep 15;
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P YourStrong!Passw0rd -i /init.sql;
      "
    volumes:
      - ./db/init.sql:/init.sql
    networks:
      - webapp-net
      
  webapp:
    build:
      context: ./WebApp
      dockerfile: Dockerfile
    container_name: webapp
    depends_on:
      - sqlserver
    ports:
      - "5000:5231"  # O ajustá si tu app usa otro puerto
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MyDb;User=sa;Password=YourStrong!Passw0rd;
    networks:
      - webapp-net

networks:
  webapp-net:

volumes:
  sqlserverdata:
