apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-build
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone https://github.com/Ameteratzu/web-app-v1.2.git /workspace/source
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      command:
        - /kaniko/executor
      args:
        - "--dockerfile=/workspace/source/WebApp/Dockerfile"
        - "--context=/workspace/source/WebApp"
        - "--destination=$(params.IMAGE)"
