apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: docker-build-template
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: docker-build-run-
      spec:
        serviceAccountName: pipeline-account
        pipelineRef:
          name: docker-build-pipeline
        params:
          - name: IMAGE
            value: docker.io/Ameteratzu/webapp-backend:latest
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              metadata:
                name: docker-build-pvc
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 1Gi
