//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGPCE.Sigemad.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DGPCE.Sigemad.Application.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clase de Suceso es obligatorio.
        /// </summary>
        internal static string ClaseSucesoObligatorio {
            get {
                return ResourceManager.GetString("ClaseSucesoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denominacion no puede exceder los 255 caracteres.
        /// </summary>
        internal static string DenominacionMaxLength {
            get {
                return ResourceManager.GetString("DenominacionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neutral.
        /// </summary>
        internal static string DenominacionNoVacio {
            get {
                return ResourceManager.GetString("DenominacionNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denominacion es obligatorio.
        /// </summary>
        internal static string DenominacionObligatorio {
            get {
                return ResourceManager.GetString("DenominacionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Suceso es obligatorio.
        /// </summary>
        internal static string EstadoSucesoObligatorio {
            get {
                return ResourceManager.GetString("EstadoSucesoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Inicio es obligatoria.
        /// </summary>
        internal static string FechaInicioObligatorio {
            get {
                return ResourceManager.GetString("FechaInicioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La geometría no es válida, sistema de referencia no es Wgs84.
        /// </summary>
        internal static string GeoPosicionInvalida {
            get {
                return ResourceManager.GetString("GeoPosicionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GeoPosicion es obligatorio.
        /// </summary>
        internal static string GeoPosicionObligatorio {
            get {
                return ResourceManager.GetString("GeoPosicionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id no puede ser vacio.
        /// </summary>
        internal static string IdNoVacio {
            get {
                return ResourceManager.GetString("IdNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id es obligatorio.
        /// </summary>
        internal static string IdObligatorio {
            get {
                return ResourceManager.GetString("IdObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio es inválido.
        /// </summary>
        internal static string MunicipioInvalido {
            get {
                return ResourceManager.GetString("MunicipioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio es obligatorio.
        /// </summary>
        internal static string MunicipioObligatorio {
            get {
                return ResourceManager.GetString("MunicipioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pais es inválido.
        /// </summary>
        internal static string PaisInvalido {
            get {
                return ResourceManager.GetString("PaisInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pais es obligatorio.
        /// </summary>
        internal static string PaisObligatorio {
            get {
                return ResourceManager.GetString("PaisObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia es inválido.
        /// </summary>
        internal static string ProvinciaInvalido {
            get {
                return ResourceManager.GetString("ProvinciaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia es obligatoria.
        /// </summary>
        internal static string ProvinciaObligatorio {
            get {
                return ResourceManager.GetString("ProvinciaObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neutral.
        /// </summary>
        internal static string TerritorioInvalido {
            get {
                return ResourceManager.GetString("TerritorioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neutral.
        /// </summary>
        internal static string TerritorioObligatorio {
            get {
                return ResourceManager.GetString("TerritorioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación no puede ser vacio.
        /// </summary>
        internal static string UbicacionNoVacio {
            get {
                return ResourceManager.GetString("UbicacionNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación es obligatorio.
        /// </summary>
        internal static string UbicacionObligatorio {
            get {
                return ResourceManager.GetString("UbicacionObligatorio", resourceCulture);
            }
        }
    }
}
