//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGPCE.Sigemad.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DGPCE.Sigemad.Application.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La lista de áreas afectadas no puede ser nula..
        /// </summary>
        public static string AreaAfectadaNoNulo {
            get {
                return ResourceManager.GetString("AreaAfectadaNoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La lista de áreas afectadas no puede estar vacía..
        /// </summary>
        public static string AreaAfectadaVacio {
            get {
                return ResourceManager.GetString("AreaAfectadaVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto no puede superar 500 caracteres.
        /// </summary>
        public static string AsuntoMaxLegth {
            get {
                return ResourceManager.GetString("AsuntoMaxLegth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto es obligatorio.
        /// </summary>
        public static string AsuntoNoNulo {
            get {
                return ResourceManager.GetString("AsuntoNoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto no puede ser vacio.
        /// </summary>
        public static string AsuntoNoVacio {
            get {
                return ResourceManager.GetString("AsuntoNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoridad que dirige no puede estar en blanco.
        /// </summary>
        public static string AutoridadQueDirigeEnBlanco {
            get {
                return ResourceManager.GetString("AutoridadQueDirigeEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoridad Que Dirige es obligatorio.
        /// </summary>
        public static string AutoridadQueDirigeObligatorio {
            get {
                return ResourceManager.GetString("AutoridadQueDirigeObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clase de Suceso es obligatorio.
        /// </summary>
        public static string ClaseSucesoObligatorio {
            get {
                return ResourceManager.GetString("ClaseSucesoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La lista de coordinaciones es obligatorio.
        /// </summary>
        public static string CoordinacionesObligatorio {
            get {
                return ResourceManager.GetString("CoordinacionesObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Principal son obligatorios.
        /// </summary>
        public static string DatoPrincipalObligatorio {
            get {
                return ResourceManager.GetString("DatoPrincipalObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominacion no puede exceder los 255 caracteres.
        /// </summary>
        public static string DenominacionMaxLength {
            get {
                return ResourceManager.GetString("DenominacionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string DenominacionNoVacio {
            get {
                return ResourceManager.GetString("DenominacionNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominacion es obligatorio.
        /// </summary>
        public static string DenominacionObligatorio {
            get {
                return ResourceManager.GetString("DenominacionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion no puede exceder los 255 caracteres.
        /// </summary>
        public static string DescripcionMaxLength {
            get {
                return ResourceManager.GetString("DescripcionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion es obligatorio.
        /// </summary>
        public static string DescripcionObligatorio {
            get {
                return ResourceManager.GetString("DescripcionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las lista de direcciones es obligatorio.
        /// </summary>
        public static string DireccionesObligatorio {
            get {
                return ResourceManager.GetString("DireccionesObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad Menor es obligatorio.
        /// </summary>
        public static string EntidadMenorObligatorio {
            get {
                return ResourceManager.GetString("EntidadMenorObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de Suceso es obligatorio.
        /// </summary>
        public static string EstadoSucesoObligatorio {
            get {
                return ResourceManager.GetString("EstadoSucesoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolucion es obligatorio.
        /// </summary>
        public static string EvolucionObligatorio {
            get {
                return ResourceManager.GetString("EvolucionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaHora no puede ser vacio.
        /// </summary>
        public static string FechaHoraNoVacio {
            get {
                return ResourceManager.GetString("FechaHoraNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha hora es obligatoria.
        /// </summary>
        public static string FechaHoraObligatorio {
            get {
                return ResourceManager.GetString("FechaHoraObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaHoraSolicitud es obligatoria.
        /// </summary>
        public static string FechaHoraSolicitudObligatorio {
            get {
                return ResourceManager.GetString("FechaHoraSolicitudObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Inicio debe ser menor que Fecha Fin.
        /// </summary>
        public static string FechaInicioDebeSerMenorQueFechaFin {
            get {
                return ResourceManager.GetString("FechaInicioDebeSerMenorQueFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Inicio es obligatoria.
        /// </summary>
        public static string FechaInicioObligatorio {
            get {
                return ResourceManager.GetString("FechaInicioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha inicio PMA es obligatoria.
        /// </summary>
        public static string FechaInicioPMAObligatorio {
            get {
                return ResourceManager.GetString("FechaInicioPMAObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La geometría CECOPI no es válida, sistema de referencia no es Wgs84.
        /// </summary>
        public static string GeoPosicionCECOPInvalida {
            get {
                return ResourceManager.GetString("GeoPosicionCECOPInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoPosicion CECOPI es obligatoria.
        /// </summary>
        public static string GeoPosicionCECOPIObligatoria {
            get {
                return ResourceManager.GetString("GeoPosicionCECOPIObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La geometría no es válida, sistema de referencia no es Wgs84.
        /// </summary>
        public static string GeoPosicionInvalida {
            get {
                return ResourceManager.GetString("GeoPosicionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoPosicion es obligatorio.
        /// </summary>
        public static string GeoPosicionObligatorio {
            get {
                return ResourceManager.GetString("GeoPosicionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La geometría PMA no es válida, sistema de referencia no es Wgs84.
        /// </summary>
        public static string GeoPosicionPMAInvalida {
            get {
                return ResourceManager.GetString("GeoPosicionPMAInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoPosicion PMA es obligatorio.
        /// </summary>
        public static string GeoPosicionPMAObligatoria {
            get {
                return ResourceManager.GetString("GeoPosicionPMAObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdArchivo es obligatorio.
        /// </summary>
        public static string IdArchivoObligatorio {
            get {
                return ResourceManager.GetString("IdArchivoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de lista Entrada/Salida es obligatorio.
        /// </summary>
        public static string IdEntradaSalidaObligatorio {
            get {
                return ResourceManager.GetString("IdEntradaSalidaObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de estado incendio es obligatorio.
        /// </summary>
        public static string IdEstadoIncendioObligatorio {
            get {
                return ResourceManager.GetString("IdEstadoIncendioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de lista de medios es obligatorio.
        /// </summary>
        public static string IdMedioObligatorio {
            get {
                return ResourceManager.GetString("IdMedioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id no puede ser vacio.
        /// </summary>
        public static string IdNoVacio {
            get {
                return ResourceManager.GetString("IdNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id es obligatorio.
        /// </summary>
        public static string IdObligatorio {
            get {
                return ResourceManager.GetString("IdObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Suceso asociado no puede ser vacio.
        /// </summary>
        public static string IdSucesoAsociadoNoVacio {
            get {
                return ResourceManager.GetString("IdSucesoAsociadoNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id suceso asociado es oblogatorio.
        /// </summary>
        public static string IdSucesoAsociadoObligatorio {
            get {
                return ResourceManager.GetString("IdSucesoAsociadoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Suceso es obligatorio.
        /// </summary>
        public static string IdSucesoObligatorio {
            get {
                return ResourceManager.GetString("IdSucesoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Suceso principal no puede ser vacio.
        /// </summary>
        public static string IdSucesoPrincipalNoVacio {
            get {
                return ResourceManager.GetString("IdSucesoPrincipalNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Suceso principal es obligatorio.
        /// </summary>
        public static string IdSucesoPrincipalObligatorio {
            get {
                return ResourceManager.GetString("IdSucesoPrincipalObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Tipo de Direccion es inválido.
        /// </summary>
        public static string IdTipoDireccionEmergenciaInvalido {
            get {
                return ResourceManager.GetString("IdTipoDireccionEmergenciaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdTipoDocumento es invalido.
        /// </summary>
        public static string IdTipoDocumentoInvalido {
            get {
                return ResourceManager.GetString("IdTipoDocumentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdTipoDocumento es obligatorio.
        /// </summary>
        public static string IdTipoDocumentoObligatorio {
            get {
                return ResourceManager.GetString("IdTipoDocumentoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Incendio no puede estar vacio.
        /// </summary>
        public static string IncendioIdNoVacio {
            get {
                return ResourceManager.GetString("IncendioIdNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Incendio es obligatorio.
        /// </summary>
        public static string IncendioIdObligatorio {
            get {
                return ResourceManager.GetString("IncendioIdObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incendio es inválido.
        /// </summary>
        public static string IncendioInvalido {
            get {
                return ResourceManager.GetString("IncendioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incendio es obligatorio.
        /// </summary>
        public static string IncendioObligatorio {
            get {
                return ResourceManager.GetString("IncendioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Otra información es obligatorio.
        /// </summary>
        public static string ListaOtraInformacion {
            get {
                return ResourceManager.GetString("ListaOtraInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El lugar es obligatorio.
        /// </summary>
        public static string LugarObligatorio {
            get {
                return ResourceManager.GetString("LugarObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MedioId no puede ser vacio.
        /// </summary>
        public static string MedioIdNoVacio {
            get {
                return ResourceManager.GetString("MedioIdNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MedioId es obligatorio.
        /// </summary>
        public static string MedioIdObligatorio {
            get {
                return ResourceManager.GetString("MedioIdObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio CECOPI es invalido.
        /// </summary>
        public static string MunicipioCECOPIInvalido {
            get {
                return ResourceManager.GetString("MunicipioCECOPIInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio CECOPI es Obligatorio.
        /// </summary>
        public static string MunicipioCECOPIObligatorio {
            get {
                return ResourceManager.GetString("MunicipioCECOPIObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio es inválido.
        /// </summary>
        public static string MunicipioInvalido {
            get {
                return ResourceManager.GetString("MunicipioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio es obligatorio.
        /// </summary>
        public static string MunicipioObligatorio {
            get {
                return ResourceManager.GetString("MunicipioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio CECOPI es invalido.
        /// </summary>
        public static string MunicipioPMAiInvalido {
            get {
                return ResourceManager.GetString("MunicipioPMAiInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio PMA es Obligatorio.
        /// </summary>
        public static string MunicipioPMAObligatorio {
            get {
                return ResourceManager.GetString("MunicipioPMAObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observación es obligatorio.
        /// </summary>
        public static string ObservacionObligatorio {
            get {
                return ResourceManager.GetString("ObservacionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais es inválido.
        /// </summary>
        public static string PaisInvalido {
            get {
                return ResourceManager.GetString("PaisInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais es obligatorio.
        /// </summary>
        public static string PaisObligatorio {
            get {
                return ResourceManager.GetString("PaisObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de parámetros son obligatorio.
        /// </summary>
        public static string ParametroObligatorio {
            get {
                return ResourceManager.GetString("ParametroObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de procedencia/Destino es obligatorio.
        /// </summary>
        public static string ProcedenciasDestinosObligatorio {
            get {
                return ResourceManager.GetString("ProcedenciasDestinosObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia CECOPI es invalido.
        /// </summary>
        public static string ProvinciaCECOPIInvalido {
            get {
                return ResourceManager.GetString("ProvinciaCECOPIInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia CECOPI es obligatorio.
        /// </summary>
        public static string ProvinciaCECOPIObligatorio {
            get {
                return ResourceManager.GetString("ProvinciaCECOPIObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia es inválido.
        /// </summary>
        public static string ProvinciaInvalido {
            get {
                return ResourceManager.GetString("ProvinciaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia es obligatoria.
        /// </summary>
        public static string ProvinciaObligatorio {
            get {
                return ResourceManager.GetString("ProvinciaObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia PMA es invalido.
        /// </summary>
        public static string ProvinciaPMAInvalido {
            get {
                return ResourceManager.GetString("ProvinciaPMAInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia PMA es obligatorio.
        /// </summary>
        public static string ProvinciaPMAObligatorio {
            get {
                return ResourceManager.GetString("ProvinciaPMAObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de Registros son obligatorio.
        /// </summary>
        public static string RegistroObligatorio {
            get {
                return ResourceManager.GetString("RegistroObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string TerritorioInvalido {
            get {
                return ResourceManager.GetString("TerritorioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string TerritorioObligatorio {
            get {
                return ResourceManager.GetString("TerritorioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo dirección emergencia es invalido.
        /// </summary>
        public static string TipoDireccionEmergenciaInvalido {
            get {
                return ResourceManager.GetString("TipoDireccionEmergenciaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo dirección emergencia es obligatorio.
        /// </summary>
        public static string TipoDireccionEmergenciaObligatorio {
            get {
                return ResourceManager.GetString("TipoDireccionEmergenciaObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación no puede ser vacio.
        /// </summary>
        public static string UbicacionNoVacio {
            get {
                return ResourceManager.GetString("UbicacionNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación es obligatorio.
        /// </summary>
        public static string UbicacionObligatorio {
            get {
                return ResourceManager.GetString("UbicacionObligatorio", resourceCulture);
            }
        }
    }
}
