//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGPCE.Sigemad.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DGPCE.Sigemad.Application.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clase de Suceso es obligatorio.
        /// </summary>
        internal static string ClaseSucesoObligatorio {
            get {
                return ResourceManager.GetString("ClaseSucesoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominacion no puede exceder los 255 caracteres.
        /// </summary>
        internal static string DenominacionMaxLength {
            get {
                return ResourceManager.GetString("DenominacionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        internal static string DenominacionNoVacio {
            get {
                return ResourceManager.GetString("DenominacionNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominacion es obligatorio.
        /// </summary>
        internal static string DenominacionObligatorio {
            get {
                return ResourceManager.GetString("DenominacionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de Suceso es obligatorio.
        /// </summary>
        internal static string EstadoSucesoObligatorio {
            get {
                return ResourceManager.GetString("EstadoSucesoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Inicio es obligatoria.
        /// </summary>
        internal static string FechaInicioObligatorio {
            get {
                return ResourceManager.GetString("FechaInicioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La geometría no es válida, sistema de referencia no es Wgs84.
        /// </summary>
        internal static string GeoPosicionInvalida {
            get {
                return ResourceManager.GetString("GeoPosicionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoPosicion es obligatorio.
        /// </summary>
        internal static string GeoPosicionObligatorio {
            get {
                return ResourceManager.GetString("GeoPosicionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio es inválido.
        /// </summary>
        internal static string MunicipioInvalido {
            get {
                return ResourceManager.GetString("MunicipioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio es obligatorio.
        /// </summary>
        internal static string MunicipioObligatorio {
            get {
                return ResourceManager.GetString("MunicipioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais es inválido.
        /// </summary>
        internal static string PaisInvalido {
            get {
                return ResourceManager.GetString("PaisInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais es obligatorio.
        /// </summary>
        internal static string PaisObligatorio {
            get {
                return ResourceManager.GetString("PaisObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia es inválido.
        /// </summary>
        internal static string ProvinciaInvalido {
            get {
                return ResourceManager.GetString("ProvinciaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia es obligatoria.
        /// </summary>
        internal static string ProvinciaObligatorio {
            get {
                return ResourceManager.GetString("ProvinciaObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        internal static string TerritorioInvalido {
            get {
                return ResourceManager.GetString("TerritorioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        internal static string TerritorioObligatorio {
            get {
                return ResourceManager.GetString("TerritorioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación no puede ser vacio.
        /// </summary>
        internal static string UbicacionNoVacio {
            get {
                return ResourceManager.GetString("UbicacionNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación es obligatorio.
        /// </summary>
        internal static string UbicacionObligatorio {
            get {
                return ResourceManager.GetString("UbicacionObligatorio", resourceCulture);
            }
        }
    }
}
