apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ameteratzu/web-app-v1.2.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
